version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      STORAGE_STRATEGY: object-storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hello_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STORAGE_OBJECT_ENDPOINT: http://minio:9000
      STORAGE_OBJECT_ACCESSKEY: minioadmin
      STORAGE_OBJECT_SECRETKEY: minioadmin
      STORAGE_OBJECT_BUCKET: packages

volumes:
  pgdata:
  minio-data:
